config/routes.rb
Rails.application.routes.draw do
  root "top#top"
  resources :shops, only: %i[index show]
  resources :posts, only: %i[index]
  namespace :api do
    get 'current_user', to: 'current_users#show'
    get 'my_list', to: 'my_pages#my_list'
    resources :posts
    resources :comments, only: %i[index create destroy] do
      resource :replies, only: %i[index create destroy], controller: 'replies'
      get 'replies', to: 'replies#index'
    end

    resources :profiles, param: :user_name, only: [:show, :update]
    get 'profiles/:user_name/posts', to: 'profiles#user_posts'

    post 'profiles/:user_name/relationships', to: 'relationships#create'
    delete 'profiles/:user_name/relationships', to: 'relationships#destroy'
    get 'follow/followings', to: 'relationships#followings'
    get 'follow/followers', to: 'relationships#followers'
    get 'follow_posts', to: 'relationships#follow_posts'

    get 'notifications', to: 'notifications#unchecked_notifications'

    resources :likes, only: [:create, :destroy]
    resources :shops, only: %i[index show] do
      collection do
        get 'search'
        post :nearest
      end
    end
    resource :current_user, only: %i[show]
    resources :visits, only: %i[show update], param: :user_id
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrarions: 'users/registrations'
  }

  get 'privacy_policy', to: 'top#privacy_policy'
  get 'terms_of_use', to: 'top#terms_of_use'
  get 'features', to: 'top#features'

  get "up", to: "rails/health#show", as: :rails_health_check

  get 'my_list', to: 'my_pages#my_list'

  get 'profiles/:user_name', to: 'profiles#show', as: :user_profile

  get 'follow', to: 'relationships#show'

  get 'follow_posts', to: 'relationships#follow_posts'

  resources :notifications, only: %i[index]

  resources :contacts, only: [:new, :create]

  get '/sitemap', to: redirect("#{ENV['SITEMAPS_HOST']}/sitemap.xml.gz")

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', optional: true
  belongs_to :visited, class_name: 'User', optional: true
end

app/controllers/api/notifications_controller.rb
class Api::NotificationsController < ApplicationController
  def unchecked_notifications
    notifications = current_user.passive_notifications.where(checked: false)
    render json: notifications, status: :ok
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.includes(:visitor, :visited, :post, :comment)
    @notifications.update_all(checked: true)
  end
end

app/helpers/api/notifications_helper.rb
module Api::NotificationsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<div class="mx-auto m-6 flex flex-col justify-center items-center ">
  <div class="w-full max-w-md">
    <span>
      <%= link_to user_profile_path(user_name: visitor.name) do %>
        <strong>
          <%= visitor.name %>
        </strong>
      <% end %>
      さんが
    </span>
    <% case notification.action %>
    <% when 'follow' %>
      <%= "あなたをフォローしました" %>
    <% when 'like' %>
      <%= link_to 'あなたの投稿', shop_path(notification.post.shop_id), style: "font-weight: bold;" %>
      <%= "にいいねしました" %>
    <% when 'comment' %>
      <%= link_to "あなたの投稿", shop_path(notification.post.shop_id), style: "font-weight: bold;" %>
      <%= "にコメントしました" %>
    <% when 'reply' %>
      <%= link_to "あなたのコメント", shop_path(notification.comment.post.shop_id), style: "font-weight: bold;" %>
      <%= "にリプライしました" %>
    <% end %>
    <div class="text-xs">
      <%= time_ago_in_words(notification.created_at).upcase + '前' %>
    </div>
  </div>
  <hr>
</div>

app/views/notifications/index.html.erb
<% content_for :title, "通知" %>
<div class="flex-1">
  <div class="m-4">
    <div class="container mx-auto">
      <% notifications = @notifications.where.not(visitor_id: current_user.id) %>
      <% if notifications.exists? %>
        <%= render notifications %>
      <% else %>
        <p>
          | 通知はありません
        <p>
      <% end %>
    </div>
  </div>
</div>