config/routes.rb
Rails.application.routes.draw do
  root "top#top"
  resources :shops, only: %i[index show]
  resources :posts, only: %i[index]
  namespace :api do
    get 'current_user', to: 'current_users#show'
    get 'my_list', to: 'my_pages#my_list'
    resources :posts
    resources :comments, only: %i[index create destroy] do
      resource :replies, only: %i[index create destroy], controller: 'replies'
      get 'replies', to: 'replies#index'
    end

    resources :profiles, param: :user_name, only: [:show, :update]
    get 'profiles/:user_name/posts', to: 'profiles#user_posts'

    post 'profiles/:user_name/relationships', to: 'relationships#create'
    delete 'profiles/:user_name/relationships', to: 'relationships#destroy'
    get 'follow/followings', to: 'relationships#followings'
    get 'follow/followers', to: 'relationships#followers'
    get 'follow_posts', to: 'relationships#follow_posts'

    get 'notifications', to: 'notifications#unchecked_notifications'

    resources :likes, only: [:create, :destroy]
    resources :shops, only: %i[index show] do
      collection do
        get 'search'
        post :nearest
      end
    end
    resource :current_user, only: %i[show]
    resources :visits, only: %i[show update], param: :user_id
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'omniauth_callbacks',
    registrarions: 'users/registrations'
  }

  get 'privacy_policy', to: 'top#privacy_policy'
  get 'terms_of_use', to: 'top#terms_of_use'
  get 'features', to: 'top#features'

  get "up", to: "rails/health#show", as: :rails_health_check

  get 'my_list', to: 'my_pages#my_list'

  get 'profiles/:user_name', to: 'profiles#show', as: :user_profile

  get 'follow', to: 'relationships#show'

  get 'follow_posts', to: 'relationships#follow_posts'

  resources :notifications, only: %i[index]

  resources :contacts, only: [:new, :create]

  get '/sitemap', to: redirect("#{ENV['SITEMAPS_HOST']}/sitemap.xml.gz")

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/shared/_before_login_header.html.erb
<header class="flex navbar h-16 bg-[#192f60] sticky top-0 z-50">
  <div class="flex-none">
    <div class="drawer">
      <input id="m-drawer" type="checkbox" class="drawer-toggle" />
      <div class="drawer-content">
        <label for="m-drawer" class="btn btn-square btn-ghost" id="menu-icon">
        </label>
      </div>
      <div class="drawer-side z-50">
        <label for="m-drawer" aria-label="close sidebar" class="drawer-overlay"></label> 
        <ul class="menu p-4 min-h-full bg-[#d4dcd6]">
          <li><%= link_to "アカウント作成", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "店舗検索", shops_path %></li>
          <li><%= link_to "みんなの新着投稿", posts_path %></li>
          <li><%= link_to "機能について", features_path %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="flex-1">
    <%= link_to root_path do %>
      <span class="text-white">こどぐるサーチ</span>
    <% end %>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false" class="bg-red-500 pr-2">
    <ul class="list-disc list-inside ml-2">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% next if message_type == 'timedout' %>
  <div class="<%= flash_background_color(message_type) %> px-4 py-2 text-white" id="flash">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-4 bg-[#e5e4e6] text-base-content">
  <aside class='flex'>
    <%= link_to '利用規約', terms_of_use_path, class: 'hover:text-gray-500', target: :_blank %>
    |
    <%= link_to 'プライバシーポリシー', privacy_policy_path, class: 'hover:text-gray-500', target: :_blank %>
    |
    <%= link_to 'お問い合わせ', new_contact_path( user_id: current_user&.id ), class: 'hover:text-gray-500', target: :_blank %>
    |
    <%= link_to 'X', 'https://twitter.com/kodoguru_search', class: 'hover:text-gray-500', target: :_blank %>
  </aside>
</footer>

app/views/shared/_login_header.html.erb
<header class="flex navbar h-16 bg-[#192f60] sticky top-0 z-50 text-xs sm:text-xl">
  <div class="flex-none">
    <div class="drawer">
      <input id="m-drawer" type="checkbox" class="drawer-toggle" />
      <div class="drawer-content">
        <label for="m-drawer" class="btn btn-square btn-ghost" id="menu-icon">
        </label>
      </div>
      <div class="drawer-side z-50">
        <label for="m-drawer" aria-label="close sidebar" class="drawer-overlay"></label> 
        <ul class="menu min-h-full bg-[#d4dcd6]">
          <li><%= link_to "店舗検索", shops_path %></li>
          <li><%= link_to "みんなの新着投稿", posts_path %></li>
          <li><%= link_to "フォロー新着投稿", follow_posts_path %></li>
          <li><%= link_to "フォロー一覧", follow_path %></li>
          <li><%= link_to "マイプロフィール", user_profile_path(current_user.name) %></li>
          <li><%= link_to "マイリスト", my_list_path%></li>
          <li><%= link_to "ユーザー情報", edit_user_registration_path %></li>
          <li><%= link_to "機能について", features_path %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="flex-1">
    <%= link_to root_path do %>
      <span class="text-white">こどぐるサーチ</span>
    <% end %>
    <%= link_to notifications_path do %>
      <div id="notification" class="ml-4"></div>
    <% end %>
  </div>
  <div class="justify-end text-white hover:text-slate-300 p-4">
    <%= link_to "ログアウト", destroy_user_session_path , data: {turbo_method: :delete, turbo_confirm: "ログアウトしますか？"} %>
  </div>
</header>